// We should not break outside a loop
package main
func main() {
  switch 1 {
    case 1: continue
  }
}
